### PR TITLE
Added tests, fixed a couple of bugs, added new feature

### PR DESCRIPTION
**Pull request by crashkonijn**
Hi there!

I've been planning to use this package for one of my project in the near future, but after a lot of thinking I came to the conclusion that I would need a new feature in this package since that would benefit my project the most: Being able to select a version based on a moment in time.

So what's the use case for this you ask? Let's say you have a Product and an Order model, an order can contain products. Because it's possible for a product to be updated (price) you might want to save the total amount that had to be payed in the order model to make sure the price of your order doesn't change.

The change that's included lets you do something more awesome, if you make the price versionable:

```PHP
class Order
{
    public function products()
    {
        return $this->belongsToMany()->moment($this->created_at);
    }
}
```

## Fixes
- Apparently I made the exact same fix as this: https://github.com/ProAI/eloquent-versioning/pull/14
- https://github.com/ProAI/eloquent-versioning/issues/15
- Model::create() didn't set the latest_version, bricking things when updating that same model afterwards
- Neither did update and save if I remember correctly

## Tests
Because having tests is the key to having a stable, maintainable opensource project I added some tests. It doesn't fully cover everything yet but it does provide a nice base to add more tests where needed. Currently this is the coverage:

capture

## Notes
- It appears my computer thought it would be wise to change the line endings on some scripts. Sorry for the diff mess this gives.
- The min PHP version has been updated to >= 7.1 due to phpunit requirements.

I hope you can accept this merge request, if there's any problems I'm glad to get your feedback.

Cheers!

### CODE REVIEW

**Comment by markusjwetzel** [comment]
Thank you very much for the pull request, @crashkonijn! I have to say that currently I don't use this package in production, so it is kind of unmaintained, but I'm willing to assist everybody who wants to improve to this package.

It seems to me that you have some good ideas for this package and also put a lot of work into this pull request. If it is okay for you, I will give you collaborator rights, so you can merge pull requests yourself.

For the line endings: It would be nice to have clean diffs. Can you please try to fix the line endings? I think most editors these days have some settings for line endings, so this shouldn't be a big deal. If you can't find a fix, then please split up the pull request into two (first one for the line ending changes and second one for the other diffs).

**Comment by crashkonijn** [comment]
Hello @markusjwetzel!

Thanks for giving me this opportunity, I'd be glad to become a maintainer of this package! I'll fix the line endings and merge it tonight.

Thanks!

**Comment by crashkonijn** [comment]
I've changed the line endings, but I'll wait with merging for now since I'd like to try and get automated testing working on this package.

Something like https://scrutinizer-ci.com/, which is free for open source projects!

**Comment by markusjwetzel** [comment]
Thanks! I've approved your request for scrutinizer ci.

**Comment by crashkonijn** [comment]
Thanks!

Unfortunately scrutinizer still doesn't allow me to add this project, I've send them a question about it. If I can't get that working by tomorrow I'll just merge this branch for now.

In the meantime I did increase code coverage:

capture_02

**Comment by markusjwetzel** [comment]
@crashkonijn I've added this repo to my scrutinizer account. It's the first time I use scrutinizer, but it seems to me that everything is set up now. If not, just let me know. :)

**Comment by crashkonijn** [comment]
@markusjwetzel awesome thanks!

**Pull request merged**
